### ISSUE TITLE
Errors when I set BrotliCompressionLevel

### ISSUE THREAD

**Issue by malchata** [kjdev/apache-mod-brotli#1]
Hello!

This is a great module and generally works pretty well so far. So thank you for that!

Sometimes when I set the BrotliCompressionLevel flag (which I had to suss out by looking at the source code) I get a 500 server error and this pops up in my error_log file:

[Wed Jun 22 19:34:11.535954 2016] [brotli:error] [pid 15722:tid 123145302839296] [client 127.0.0.1:50773] AH01386: Brotli compress error

This will happen when I set the compression level to 1, which is a valid setting since Brotli quality can be specified from 1 to 11.

I'd love to see this get a fix. I want to write an article on using this for Apache sites.

Otherwise, this is a great module and seems to work quite nicely! Good work!

**Comment by kjdev** [comment]
Although I tried to test, I did not have an error.

```
LoadModule brotli_module modules/mod_brotli.so
AddOutputFilterByType BROTLI application/javascript
BrotliCompressionLevel 0
# or BrotliCompressionLevel: 1
# or BrotliCompressionLevel: 10
```

```
% siege -r 100 -c 100 --header 'Accept-Encoding: br' http://localhost/js/d3.min.js   # /path/to/js/d3.min.js (126569 B)
..
Transactions:            10000 hits
Availability:           100.00 %
..
Successful transactions: 10000
Failed transactions:         0
..
```

Please tell me the pattern where the error occurs.

**Comment by malchata** [comment]
Can BrotliCompressionLevel be set from 1 to 11? Or is it zero-indexed to be 0-10?

**Comment by kjdev** [comment]
BrotliCompressionLevel Range is 0 to 11. (Including 0, 11)

**Comment by malchata** [comment]
Thanks for your help. Closing this since I've been using the module on my site without issue, and all seems to work well.
