### ISSUE TITLE
Serve brotli over gzip

### ISSUE THREAD

**Issue by ericmagnuson** [kjdev/apache-mod-brotli#13]
I have many VirtualHosts on my Apache2 server.  Only one VirtualHost is correctly serving brotli-compressed files over gzip-compressed files.  For all other requests to other domains on the same server, gzip-compressed files are being served.  When I turn off mod_deflate, brotli still isn't functioning — instead all the files are served without compression.

Has anyone else experienced similar problems with mod_brotli only working on certain VHosts?

**Comment by ericmagnuson** [comment]
Figured it out.  The problem was not with mod_brotli.  I use Varnish as a front-end cache, and it was modifying the `Accept-Encoding` header before the request hit Apache.

For others who might have this same problem with Varnish, start Varnish with http_gzip_support off.  For me, I had to edit `/etc/systemd/system/multi-user.target.wants/varnish.service` and tell it to start varnishd with the flag `-p http_gzip_support=off`.

**Comment by cherouvim** [comment]
Turning `http_gzip_support` to `off` works, but note that it means that varnish will no longer normalize the `accept-encoding` header. This results in many more requests reaching the backend and multiple versions of the same content stored in varnish.
